//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagementDbEntities : DbContext
    {
        public ManagementDbEntities()
            : base("name=ManagementDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Counters> Counters { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Patches> Patches { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<StockInRecords> StockInRecords { get; set; }
        public virtual DbSet<StockOutRecords> StockOutRecords { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
