//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInRecords
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public string ProductUnit { get; set; }
        public string ProductNotes { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
