//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutRecords
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContactPerson { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerAddress { get; set; }
        public string InvoiceNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public string ProductUnit { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string ProductNotes { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<double> ProductTotalAmount { get; set; }
    }
}
